export default function Home({ isLoggedIn }) {
  return (
    <div>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
      <h1>ciao</h1>
    </div>
  );
}
